[tool.pyright]
typeCheckingMode = "basic"
useLibraryCodeForTypes = true
reportPrivateUsage = false
reportUnknownMemberType = false
reportOptionalSubscript = false
reportOptionalMemberAccess = false
reportOptionalCall = false
reportOptionalIterable = false
reportOptionalContextManager = false
reportOptionalOperand = false
reportGeneralTypeIssues = false